#!/bin/bash
# Using conditional statements in bash


read -p "Enter your age: " age # prompt for an age

# the if statement
# all the spaces should be in the right place or things don't work
if [ $age -ge 18 ]	# if age greater than or equal to 16
then
		echo "You can drive"
elif [ $age -eq 17 ]
then
		echo "You can drive next year"
else
		echo "You can't drive"
fi



read -p "Enter a number: " num

# extended if statement

if ((num == 10)); then
		echo "Your number equals 10"
elif ((num > 10)); then
		echo "Your number is greater than 10"
else
		echo " Your number is less than 10"
fi

if (( ((num % 2)) == 0 )); then
		echo "Your number is even"
else
		echo "Your number is odd"
fi
