#!/bin/bash

declare -r NUM1=5

num2=4

num3=$((NUM1+num2))
num4=$((NUM1-num2))
num5=$((NUM1*num2))
num6=$((NUM1/num2))
num7=5
$((num7+=NUM1))

echo "5 + 4 = $num3"
echo "5 - 4 = $num4"
echo "5 * 4 = $num5"
echo "5 / 4 = $num6"
echo "5^6 = $((5**6))"
echo $num7

echo "num7++ = $((num7++))"
echo "++num7 = $((++num7))"
echo "num7-- = $((num7--))"
echo "--num7 = $((--num7))"

num8=$(python -c "print 5+4")
echo "num8 = $num8"
